### ISSUE TITLE
How can i use it in AiThinkerIDE in Windows?

### ISSUE THREAD

**Issue by zuzy** [espressif/esp8266-alink-sds#1]
As what i said in the title, I want to play the demo in AiThinkerIDE but I cannot configure the project.

**Comment by shootao** [comment]
AiThinkerIDF is not Espressif official，about this,you can counsel AiThink。
thx

**Comment by zuzy** [comment]
ok, i've finished the env of ubuntu to build and upload the project. But i cannot regist the device into aliyun. Does the project adapt to Aliyun SDS or other aliyun?
I build the project successfully, but i cannot build it in ALINK_PASSTHROUGH mode. Makefile tells there is sth wrong in transport.c json_get_value_by_name

**Comment by shootao** [comment]
Hi：
    1.Ali cann't Support ALINK_PASSTHROUGH mode，so you cann't user passthough.
    2. You can consult this link to regist
https://iot.aliyun.com/docs/develop/guide.html

**Comment by zuzy** [comment]
OK, i found that alink SDS cannot support passthrough mod yet.
