### ISSUE TITLE
WiFi模块OTA升级

### ISSUE THREAD

**Issue by zuzy** [espressif/esp8266-alink-sds#2]
我现在已经成功连上了阿里云，并且配网连网和数据交互也成功了。但是我每次尝试使用阿里平台ota升级wifi模块都会出现栈溢出。有擦除超出范围报错，也有其他的报错。即使阿里云显示我升级成功，我的模块打印出来还是栈溢出重启，然后程序并没有升级成功。

**Comment by shootao** [comment]
你好：
你的是用embed原生的DK编译出现的问题吗？请提供一下log信息（请把log level 设置高一点）

**Comment by zuzy** [comment]
是的，就是clone了这个仓库并且按照readme里面介绍的方式配置的环境。


[升级失败日志.txt](https://github.com/espressif/esp8266-alink-embed/files/1196356/default.txt)

**Comment by zuzy** [comment]
\0x1b[37m<DEBUG> [alink_ota_status_post#55] : alink_ota_status_post: {"version":"1.0.3","step":"0","stepPercent":"100"}, ret=0


\0x1b[0m


platform_config_write>>len=432,content=Alink+


\0x1b[37m<DEBUG> [alink_ota_set_status#84] : !!!!!!set ota state:1\0x1b[0m


\0x1b[37m<DEBUG> [alink_ota_main_thread#130] : step:ALINK_OTA_DOWNLOAD !


\0x1b[0m


\0x1b[0;32mI alink_upgrade: system upgrade init\0x1b[0m


\0x1b[0;32mI alink_upgrade: system_upgrade_flag_set>>UPGRADE_FLAG_START\0x1b[0m


fw_bin_sec_earse:253, Out of range


flash erase over


\0x1b[0;32mI alink_upgrade: system upgrade init succeeded\0x1b[0m


\0x1b[0;32mI alink_network: alink server host: otalink.alicdn.com111111111111111\0x1b[0m


ShowCritical:1


\0x12J\0xeb\0x805\0x9d\0x94r\0xdf\0x90\0x9a\0xbcOpr\0x18\0xc5\0x04e\0xadU\0x03\0xff\0x12\0x9b\0x9b\0xfa\0x01\0xd7\0xfc\0x1c\0x8a\0x1czL\0xe39\0x8f\0xd5S#\0x01X*P\0x09\0x12\0xd0\0x04\0x00)\0xcb\0x80}\0xce\0x04~\0xe7x\0xb2 \0xc0\0x86>\0x00\0x12\0xe0\0xff\0x04\0x80\0xff9\0xcf\0x80\0xbf9\0x08\0xfa\0x18\0xb3\0x82\0x07


\0x08\0xc8\0x03\0x80\0xff\0x12\0xa4\0xff\0x04\0x00)\0xcb\0x80~\0xc6\0x0c>\0x8c\0xf1\0x80\0x03\0x05gI\0x07\0xc0\0xff


上面一条回复是我直接上传了一个user1.bin的结果。
这一次我combine成为了一个2M的bin文件尝试升级依旧失败。而且升级失败后无法再次启动，最后一行hex打印是升级失败后重启打印的结果。

**Comment by zuzy** [comment]
我使用的模块是4mb flash的型号；但是demo中都是2m 1024kb 1024kb的map；不知道这个地方是不是有影响？
另外我还想知道修改哪里可以让这个demo适配4mb 模块。

**Comment by zuzy** [comment]
发现问题erase over range 253。应该是获取了system flash map是512kb版本；没有修改过这个demo的配置；makefile中flash map一直设置是5。 会有什么地方引发这种问题呢？

**Comment by shootao** [comment]
你这是flash map问题，你看一下你在download tool勾选有没有问题

**Comment by zuzy** [comment]
哦，是我这边esptool那边没有设置fm，fs，ff这些选项。
现在的flashmap已经是2m 1024 的模式了，但是我现在sds的ota还是没有成功。
下面在我debug level的log：
UpdateCurrentTime for plan>>day4,09:52:59\0x7f~\0x03\0x81\0x03\0x01\0x85platform_config_write>>len=432,content=Alink+
esp_info_save start
esp_info_save finish check
esp_info_save index 1
g_info_manager.use_length==640
esp_info_save>>before spi_flash_read
esp_info_save>>before spi_flash_erase_sector
esp_info_save>> spi_flash_erase_sector succeed
esp_info_save>>before spi_flash_write 
esp_info_save>> spi_flash_write succeed
esp_info_save all ok
\0x1b[0;32mI alink_upgrade: system upgrade init\0x1b[0m
SendWifiStatusToMcu
serial_write ret=6
\0x7f~\0x03\0x81\0x03\0x01\0x85flash erase over
\0x1b[0;32mI alink_upgrade: system upgrade init succeeded\0x1b[0m
\0x1b[0;32mI alink_network: alink server host: otalink.alicdn.com\0x1b[0m
\0x1b[0;32mI alink_network: ip: 115.231.145.95, port: 80\0x1b[0m
SendWifiStatusToMcu
serial_write ret=6
executePlan_timer_cb>>g_bPlanEnable = false
\0x7f~\0x03\0x81\0x03\0x01\0x85SendWifiStatusToMcu
serial_write ret=6
\0x7f~\0x03\0x81\0x03\0x01\0x85\0x1b[0;31mE alink_network: [platform_tcp_recv, 341]:recv ret:-1, errno: 11\0x1b[0m
state: 5 -> 0 (0)
rm 0
pm close 7 0 0/48927265
del if0
usl
sul 0 0
\0x1b[0;31mE alink_ssl: [platform_ssl_recv, 156]:SSL_read, ret:-1, errno:103\0x1b[0m
\0x1b[33m<ERROR> [receive_worker#400] :\0x10\0xba\0x89\0xa18\0x9c)\0xd1\0x9e()\0xe3\0xf9<\B\0x88\0x01X0\0xa8%\0xf90 \0xd4\0xab\0xfe!P\0xd0\0x04\0x7f\0xc2\0xa1V\0x0b\0xd1\0xe55

然后就重启了。

**Comment by shootao** [comment]
你重启时有exception吗？如果有exception你先看一下exception原因

**Comment by zuzy** [comment]
没有，直接就打印了我一个ntp功能初始化。

**Comment by zuzy** [comment]
发现应该是阿里sds的问题，每次到80%tcp的连接都会断开，超时，然后升级失败。
